name: Publish Docker image
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}

jobs:
  debian:
    name: Debian
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get amplify-cli version
        id: amplify
        run: echo "::set-output name=version::$(npm view @aws-amplify/cli version)"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=true
          tags: |
            type=raw,value=${{ steps.amplify.outputs.version }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./.devcontainer
          build-args: AWS_AMPLIFY_CLI_VERSION=${{ steps.amplify.outputs.version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  alpine:
    name: Alpine Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get amplify-cli version
        id: amplify
        run: echo "::set-output name=version::$(npm view @aws-amplify/cli version)"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: suffix=-alpine
          tags: |
            type=raw,value=${{ steps.amplify.outputs.version }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./.devcontainer
          file: ./.devcontainer/alpine/Dockerfile
          build-args: AWS_AMPLIFY_CLI_VERSION=${{ steps.amplify.outputs.version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
